{
  lib,
  config,
  pkgs,
  ...
}: let
  cfg = config.programs.neovim;
in {
  options = {
    programs.neovim = {
      lazyVim = lib.mkEnableOption "LazyVim";
    };
  };
  config = {
    xdg.configFile = lib.mkIf cfg.lazyVim {
      "nvim/lua" = {
        source = ./nvim/lua;
        recursive = true;
      };
      "nvim/after" = {
        source = ./nvim/after;
        recursive = true;
      };
    };

    programs.neovim = {
      # package = pkgs.neovim-nightly;
      vimAlias = true;
      extraLuaPackages = luaPkgs: with luaPkgs; [luautf8];
      extraPython3Packages = pyPkgs: with pyPkgs; [pynvim];
      extraPackages = [pkgs.luajit pkgs.tree-sitter pkgs.nodePackages.nodejs];
      extraLuaConfig = lib.concatStringsSep "\n" [
        "-- Configurations generated by home-manager."
        (builtins.readFile ./nvim/lazy.lua)
      ];
    };
  };
}
