{
  lib,
  config,
  pkgs,
  ...
}: {
  xdg.configFile = {
    "nvim/lua" = {
      source = ./nvim/lua;
      recursive = true;
    };
    "nvim/after" = {
      source = ./nvim/after;
      recursive = true;
    };
  };

  programs.neovim = {
    # package = pkgs.neovim-nightly;
    vimAlias = true;
    extraLuaPackages = luaPkgs: with luaPkgs; [luautf8];
    extraPython3Packages = pyPkgs: with pyPkgs; [pynvim];
    extraPackages = builtins.attrValues {
      inherit
        (pkgs)
        luajit
        tree-sitter
        shellcheck
        shfmt
        nil
        ruff
        pyright
        black
        sumneko-lua-language-server
        stylua
        ;
      inherit
        (pkgs.nodePackages)
        nodejs
        bash-language-server
        yaml-language-server
        ;
    };
    extraLuaConfig = lib.concatStringsSep "\n" [
      "-- Configurations generated by home-manager."
      (builtins.readFile ./nvim/lazy.lua)
    ];
  };
}
